### ISSUE TITLE
replace_in_file() does not name the file in which an error occured, impeding debugging

### ISSUE THREAD

**Issue by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [pik-piam/gms#100]
https://github.com/pik-piam/gms/blob/744b94087293b92dbac6ed86a0bd3b8ddfe894fe/R/replace_in_file.R#L54-L55

[via](https://mattermost.pik-potsdam.de/rd3/pl/45c4ps93nf8w8qfww44x5zb6ph)

**Comment by tscheypidi** [comment]
re-labelled from bug to enhancement as this more sounds like a feature request to me
