### ISSUE TITLE
not so understandable codeCheck results

### ISSUE THREAD

**Issue by orichters** [pik-piam/gms#21]
Two things I identified with @robinhasse:

----
If a global switch is added to a `not_used.txt` (which apparently is not desired), the error message is:
```
2: Could not find any declaration for cm_rcp_scen_build
````
See https://github.com/remindmodel/remind/runs/6772164690. A better error message would be really desirable. By the way, where can I find a description of what is supposed to enter `not_used.txt`?

----
If code looks [like that](https://github.com/remindmodel/remind/blob/ecc4d0e72a515f9dd9ff7bb99e70a60cbefe8fc2/core/datainput.gms#L245-L246), note the indentation with blanks:
```
  Parameter
  p_extRegiccsinjecrateRegi(ext_regi) "Regional CCS injection rate factor. 1/a. (extended regions)" / %c_ccsinjecrateRegi% /;
```
a warning is raised [as in this remind PR check](https://github.com/remindmodel/remind/runs/6559037567), stating:
```
: "Parameter" does not follow the given naming convetions (description = "")!
```
But strangely enough, this warning does not impede the script from stating `All codeCheck tests passed!`. Maybe, because the warning has no parameter name but rather an empty string? It would be appreciated if incorrect blanks before stating "Parameter" etc. would get a more understandable error code.

**Comment by giannou** [comment]
> where can I find a description of what is supposed to enter `not_used.txt`?

A somewhat hidden description is found [here](https://github.com/magpiemodel/tutorials/blob/master/4_GAMScodeStructure.md#structure-within-each-realization)

**Comment by giannou** [comment]
Regarding the indentation with blanks: it happens also elsewhere in the code so maybe it's not what generates the warning?

How about the slash `/` in the description field? In any case I'm looking also into that and will report back soon

**Comment by orichters** [comment]
Reminds me of
- a similar problem here: https://github.com/pik-piam/lucode2/issues/88
- and the fix here: https://github.com/pik-piam/lucode2/pull/89

**Comment by giannou** [comment]
The
> indentation with blanks

issue was fixed with https://github.com/pik-piam/gms/pull/25.

The 
> If a global switch is added to a `not_used.txt`

issue seems to be a bug and will be treated and discussed further here.
