### ISSUE TITLE
codeCheck() references non-existent page of "Coding Etiquette"

### ISSUE THREAD

**Issue by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [pik-piam/gms#3]
https://github.com/pik-piam/gms/blob/e5165f64a6566889adad00f8fa772169eb4b2127/R/codeCheck.R#L114

http://redmine.pik-potsdam.de/projects/mo/wiki/Coding_Etiquette is dead.

**Comment by giannou** [comment]
should be fixed with https://github.com/pik-piam/gms/commit/d6b75856c0fd36b86343fc7a7a93b008f2233384, sorry!
