### ISSUE TITLE
gms::getLine hangs RStudio on windows

### ISSUE THREAD

**Issue by mikapfl** [pik-piam/gms#31]
With the most recent RStudio on windows, `gms::getLine` in RStudio's command line just hangs RStudio. In contrast, 
```r
> get_line <- function() {
+     # gets characters (line) from the terminal of from a connection
+     # and stores it in the return object
+     if (interactive()) {
+         s <- readline()
+     } else {
+         con <- file("stdin")
+         s <- readLines(con, 1, warn = FALSE)
+         on.exit(close(con))
+     }
+     return(s)
+ }
> get_line()
asdf
[1] "asdf"
> 
```
works.

Thanks to @orichters for the bug report.

**Comment by orichters** [comment]
I noticed that it does not actually hang it. You can still type in further lines. It seems that the carriage return is not correctly interpreted, so it simply doesn't stop reading input, I guess.

**Comment by mikapfl** [comment]
I think the problem is that in Rstudio some buffering happens. I can also reproduce it on linux.
