### ISSUE TITLE
codeCheck confused if parameter is added to a single not_used.txt of a module

### ISSUE THREAD

**Issue by orichters** [pik-piam/gms#44]
how to reproduce it (in REMIND):
- edit a file such as `modules/46_carbonpriceRegi/netZero/not_used.txt` and add a parameter that is definitely not used in any of the module's realizations, such as `cm_abortOnConsecFail,,` into the document.
- run `gms::codeCheck(interactive = TRUE)`
- after asking whether this can be removed from this file, it asks you whether it should add it to the other `not_used.txt` in this module. I don't think this is intended…
I tag Jan as the author and Mika who worked on this recently

**Comment by orichters** [comment]
Additionally, codeCheck removes the header starting with `# |  (C) 2006-2022 Potsdam Institute for Climate Impact Research (PIK)` from the `not_used.txt` it overwrites. Though I'm not sure this header should actually be part of these files, it doesn't seem to be part of all of them.

**Comment by mikapfl** [comment]
Maybe interactive `codeCheck` is not actually something we can maintain atm, given the relatively little gain it brings vs. the relatively high effort?

**Comment by orichters** [comment]
I think the option is valuable and this small problem can be fixed. The part with the copyright stuff is not really of relevance as we don't have this consistenly in all these files (we may simply remove it everywhere). Such a list of variables does not pass the threshold of originality anyway.
