### ISSUE TITLE
Non-matching line numbers between error messages in full.lst and full.gms

### ISSUE THREAD

**Issue by flohump** [pik-piam/gms#49]
If a MAgPIE run fails there are error messages in the full.lst with a line number like
`**** Exec Error at line 1241725: division by zero (1.48219693752374E-323)`
But the line number given does not correspond exactly the line number in the full.gms file.
Usually, the error can be found within +-100 lines of the given line number. 
This makes debugging MAgPIE runs often very tedious, espcially if there are multiple potential error sources around the given line number.   
Is this a know GAMS / CONOPT4 issue?
Or is this issue limited to MAgPIE? 
Does REMIND have the same issue?
Anyway, it would be much appreciated if line numbers in error messages would point to the exact location.

**Comment by pfuehrlich-pik** [comment]
Again I have no idea, sorry. Could this also be related to singleGAMSfile and could it be fixed if we switch to the gams native compilation as mentioned in https://github.com/pik-piam/gms/issues/48?

**Comment by mikapfl** [comment]
The error comes from GAMS, right? I think you would have to ask the GAMS developers to make more precise error messages. :slightly_frowning_face: 
Anyway, the `full.lst` file is often more helpful than the `full.log` file for finding the problem, look for the first error using `less -j 4 --pattern='^\\*\\*\\*\\*'`.

**Comment by flohump** [comment]
> Ah, sorry, you wrote that the error is in `full.lst`. Yeah, that's on the GAMS developers then, nothing we can solve. 😕

The error message above is only an example. The main point is that line number do not match with the full.gms file for any error message we have in the full.lst. file.

**Comment by mikapfl** [comment]
Okay, I understand it now. Unfortunately, `full.lst` is written by GAMS after reading `full.gms`, and the `full.gms` is not changed any more by us, so that is entirely under gams' control.

**Comment by mikapfl** [comment]
Or, to be more precise: That's how it is in REMIND, I would *think* it is the same in MAgPIE.

**Comment by tscheypidi** [comment]
I agree, it also looks to me like a GAMS issue where we really don't have any handle. I will close the issue now.
