### ISSUE TITLE
readSettings.R cannot read variable definitions with tabs

### ISSUE THREAD

**Issue by orichters** [pik-piam/gms#50]
A problem spotted with @fpiontek
```
Parameter
   cm_distrBeta              "elasticity of tax revenue redistribution";
   cm_distrBeta       = 1;         !! def = 1
```
works.

For 
```
Parameter
   cm_distrBeta              "elasticity of tax revenue redistribution";
   cm_distrBeta  /TAB/   = 1;         !! def = 1
```
(with `/TAB/` meaning an actual tabstop), `readSettings(file)` returns `Could not find value for cm_distrBeta, skipping it.`, which at least a bit helpful.

But: if you just run `./start.R config/scenario_config.csv` with a column that changes `cm_distrBeta`, the scripts just prints:
```
Automated checks did not find counterparts in default.cfg or main.gms for these config file columns:
  cm_distrBeta
start.R might simply ignore them. Please check if these switches are not deprecated.
```
which is very hard to debug, given that one has defined it in `main.gms`.

Can we either check for tabs somewhere, adopt the script that it can deal with tabs, or do something else about it? In particular, as the coding etiquette does not even mention tabs. Thanks!

**Comment by orichters** [comment]
Bzw.: Zeit für einen Test in remindmodel, dass gms::readSettings("main.gms") keine warning schmeißt?

**Comment by mikapfl** [comment]
Both good ideas, I'll look into it.

**Comment by orichters** [comment]
We have a test now that reading remind settings works without warning: https://github.com/remindmodel/remind/pull/1123
