### ISSUE TITLE
codeCheck: if a parameter is only in one not_used.txt, it suggests to add it everywhere instead of removing it

### ISSUE THREAD

**Issue by orichters** [pik-piam/gms#68]
How to reproduce:
- add new line `cm_NDC_version,input,questionnaire` to `modules/45_carbonprice/NPi/not_used.txt` of REMIND
- run `make check-fix` 
- The script asks:

```
Please choose option:

1: yes
2: no
"cm_NDC_version" is not addressed in realization "diffCurvPhaseIn2Lin" of module "carbonprice"! Does that make sense?
Number or leave empty:
1
Selected: yes


Please choose option:

1: yes
2: no
Should "cm_NDC_version" be written to not_used.txt in realization "diffCurvPhaseIn2Lin" of module "carbonprice"?
```

I think: If it is never used anywhere in the code of the module, it should be removed completely. Maybe we could also get rid of the two questions and rather have only one asked.

Tagging @tscheypidi as author of the code and @pfuehrlich-pik as master of all this R stuff :)

**Comment by pfuehrlich-pik** [comment]
I'm definitely not a master of any of the gams related R stuff :smile: Now that I think about it, I still have not written a single line of gams code, so I don't think I can help here.

**Comment by orichters** [comment]
Maybe (!) it is caused by this setglobal variable is actually used in the model realizations, except that it is a `$setglobal cm_NDC_version  2023_cond` and therefore should not be in not_used.txt. Personally, I wouldn't even care if the `not_used.txt` stuff was removed completely, I don't see any sense in it, to be honest ;)
