### ISSUE TITLE
codeCheck inconsistency: removing variables from not_used.txt lets getInterfaceInfo fail next time

### ISSUE THREAD

**Issue by orichters** [pik-piam/gms#85]
Use remindmodel [3.2.1.dev1029](https://github.com/remindmodel/remind/commit/19996bc50f1cdaf481f1b7f0215815353231f60d) and run `make check`. Everything fine, just `sm_mega_2_non` is removed from a `not_used.txt`. But: If you run `make check` immediately a second time, it will fail because `sm_mega_2_non` is not an interfaces anymore. I'm not sure how to solve that.

This lead to the fact that @LaviniaBaumstark merged https://github.com/remindmodel/remind/pull/1552, but then in https://github.com/remindmodel/remind/pull/1557 `make test` which includes codeCheck failed.
```
/p/tmp/oliverr/remind (fixmain)$ make check
Rscript -e 'invisible(gms::codeCheck(strict = TRUE))'
Global .Rprofile loaded! (R version 4.1.2 (2021-11-01))

 Running codeCheck...
 Finished data collection...            (time elapsed: 135.88)
 Naming conventions check done...       (time elapsed: 135.88)
  Running checkAppearance...
  Start variable matching...            (time elapsed:  0.062)
  Finished variable matching...         (time elapsed:   1.38)
 Investigated variable appearances...   (time elapsed: 137.34)
 Appearance and usage check done...     (time elapsed: 137.41)
 Switch Appearance check done...        (time elapsed: 137.80)
 Cleanup not_used.txt...                (time elapsed: 137.88)
'sm_mega_2_non' has been removed as interface and has been deleted from all 2 not_used.txt files of module 'CES_parameters'!

 Interface collection and check done... (time elapsed: 138.07)
 Input folder check done...             (time elapsed: 138.07)
 Description check done...              (time elapsed: 138.07)
 All codeCheck tests passed!
```
```
/p/tmp/oliverr/remind (fixmain)$ make check
Rscript -e 'invisible(gms::codeCheck(strict = TRUE))'
Global .Rprofile loaded! (R version 4.1.2 (2021-11-01))

 Running codeCheck...
 Finished data collection...            (time elapsed:  98.46)
 Naming conventions check done...       (time elapsed:  98.47)
  Running checkAppearance...
  Start variable matching...            (time elapsed:  0.058)
  Finished variable matching...         (time elapsed:   1.39)
 Investigated variable appearances...   (time elapsed:  99.94)
 Appearance and usage check done...     (time elapsed: 100.01)
 Switch Appearance check done...        (time elapsed: 100.40)
 Interface collection and check done... (time elapsed: 100.60)
 Input folder check done...             (time elapsed: 100.60)
 Description check done...              (time elapsed: 100.61)
Error in `gms::codeCheck()`:
! codeCheck returned warnings. Fix warnings to proceed!
Backtrace:
    ▆
 1. └─gms::codeCheck(strict = TRUE)
Warning message:
sm_mega_2_non appears only in "core" even though it is supposed to be an interface (perhaps only in not_used.txt?)!
Execution halted
make: *** [Makefile:61: check] Error 1
```

**Comment by LaviniaBaumstark** [comment]
in REMIND I already fixed it. I deleted the parameter. The problem is that in the first run codeCheck did not fail, but it then fails for the following versions. It is the question, how to deal with this behaviour of codeCheck()

**Comment by tscheypidi** [comment]
ah ok...so is that related to changes in #71? I guess after the automatic fixes another round of tests need to be run in order to catch that issue in the first execution

**Comment by orichters** [comment]
It is related, but not caused by it. I think such a problem might have happened before as well when it was not automatically deleted, but after a user query.

Can we just move [this part](https://github.com/pik-piam/gms/blob/4c89b71eeb39c4ba445a1d82fc6131204a27dc06/R/codeCheck.R#L284-L353) that potentially changes the code before the call to [.getInterfaceInfo()](https://github.com/pik-piam/gms/blob/4c89b71eeb39c4ba445a1d82fc6131204a27dc06/R/codeCheck.R#L229)? One might need to carefully check whether `ap` is updated correctly in order for the check to make sense.

**Comment by tscheypidi** [comment]
my guess is that the interface info is required before the part which changes the code but also afterwards again in an updated form.

**Comment by orichters** [comment]
Happened again:
- no fail because automatically removed: https://github.com/remindmodel/remind/actions/runs/8048915763/job/21981245187
- fail: https://github.com/remindmodel/remind/actions/runs/8051033598/job/21988009538

**Comment by fbenke-pik** [comment]
Lavinia suggested to fix this problem by skipping the removal when codeCheck is run as part of the Github Actions. The corresponding PR can be found here: https://github.com/pik-piam/gms/pull/90

**Comment by fbenke-pik** [comment]
After further discussion with Oliver, the preferred solution is simply running the interface check again, whenever changes were made to any not_used.txt files: https://github.com/pik-piam/gms/pull/91
