### ISSUE TITLE
`gms::getfiledestinations` typically searches all `renv` folders for `files` files

### ISSUE THREAD

**Issue by orichters** [pik-piam/gms#96]
Go to your magpie or remind folder, start `R` and run
```
library(gms)
t <- Sys.time(); d <- getfiledestinations(); print(Sys.time() - t)
```
Usually ~25 seconds. Now add `/renv/` to `.gitignore` and rerun: Around 2.5 seconds, a factor of 10.

Might be irrelevant when used within a model run, but since REMIND uses this check in `--gamscompile` mode when a user is sitting there, waiting, it is annoying.

The reason is that getfiledestination only skips top-level folders defined in `./.gitignore`, and `/renv/` isn't one of them, but the renv subfolders with all the libraries are excluded in remind and magpie in a separate `./renv/.gitignore` file.

Options I see:

1. add `ignore = NULL` option to getfiledestinations to allow to skip it from REMIND in the `--gamscompile` mode. Certainly wouldn't break anything for anyone else, but would not fix the issue for the call to getfiledestinations from `download_distribute()`
2. add `/renv/` folder to main `.gitignore` file. If something is changed within the folder, it would need to be added by `git add --force`.
3. adjust getfiledestinations such that it skips not only top-level folders, and also reads the `/renv/.gitignore` file. Might break something, no idea
4. always skip `"renv"` folder in getfiledestinations. Might break something, no idea

**Comment by tscheypidi** [comment]
@orichters I have troubles reproducing that bad performance you experienced. Running it on one of my magpie repos on the cluster I get the following:

```
> t <- Sys.time(); d <- getfiledestinations(); print(Sys.time() - t)
Time difference of 0.0680759 secs
```

**Comment by orichters** [comment]
Did you try a magpie folder where `renv` was fully installed and activated?

`/p/tmp/oliverr/NGFS_v5/remind-2024-03-27/magpie`
Time difference of 18.81181 secs

`/p/tmp/oliverr/NGFS_v5/remind-2024-03-27`
Three tries yield:
Time difference of 12.98819 secs
Time difference of 29.05453 secs
Time difference of 5.00172 secs

No idea why it is so volatile. I'm working on the old cluster, maybe this is just sometimes slow accessing the files?

**Comment by tscheypidi** [comment]
adressed in PR #97
